# bc 1.07.1: bc/libmath.h (the math library, precompiled to bc bytecode) is
# generated by running the bc just built ("./fbc -c libmath.b"), which is a
# Haiku arm64 binary here, and the tarball does not ship the header. So a
# host build of the same source generates it (the plain "cc" of the build
# environment is the cross compiler, so the compiler is named), and the cross build gets that
# file: the objects the header's make rule depends on are built first, then
# the header is copied in as the newest file, and make skips the rule.
# Configure and install as in the recipe.
BUILD()
{
	rm -rf ../bc-host
	cp -R . ../bc-host
	(
		cd ../bc-host
		CONFIG_SITE=/dev/null CC=/usr/bin/clang AR=/usr/bin/ar RANLIB=/usr/bin/ranlib \
			./configure --without-readline --without-libedit >/dev/null
		make -C lib -j1
		make -C bc -j1 libmath.h
	)
	grep -q '^{"' ../bc-host/bc/libmath.h

	runConfigure --omit-dirs "docDir dataRootDir" ./configure
	make -C lib -j1
	make -C bc -j1 main.o bc.o scan.o execute.o load.o storage.o util.o warranty.o
	cp ../bc-host/bc/libmath.h bc/libmath.h
	make -j1
}
